# Generated by Django 6.0.5 on 2026-05-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=100)),
                ('tugilgan_yili', models.IntegerField()),
                ('shahar', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('yil', models.IntegerField()),
                ('narx', models.IntegerField()),
                ('mavjud', models.BooleanField(default=True)),
                ('qoshilgan', models.DateField(auto_now_add=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitoblari', to='main.muallif')),
            ],
        ),
    ]
