# Generated by Django 5.2.14 on 2026-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ism',
                'verbose_name_plural': 'ismi',
                'db_table': 'ism',
                'ordering': ['ism'],
            },
        ),
    ]
